server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://ysmkrkftsndtqh:c04437a011a65355940801c55bf3b5867e238dc63c251c84e72ae998ce84e0d2@ec2-54-145-249-177.compute-1.amazonaws.com:5432/dljsimt13tjdl
    username: ysmkrkftsndtqh
    password: c04437a011a65355940801c55bf3b5867e238dc63c251c84e72ae998ce84e0d2
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander / Backend